apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
