apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
    version: blue  # Initially, traffic goes to Blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
